admin_port = 8081

upgrade_sock = "/tmp/pingora_upgrade.sock"
upgrade_mode = true

[servers.Server1]
addr = "0.0.0.0:6190"
upstreams = ["web", "api"]
enabled = true

[servers.Server2]
addr = "0.0.0.0:6191"
upstreams = ["admin"]
enabled = true

[servers.Server3]
addr = "0.0.0.0:6193"
upstreams = ["test"]
enabled = false

[upstreams.web]
addrs = ["127.0.0.1:8080"]
use_tls = false
sni = "www.example.com"
waf_rules = "web"

[upstreams.api]
addrs = ["127.0.0.1:8080"]
use_tls = false
sni = "api.example.com"
waf_rules = "api"

[upstreams.admin]
addrs = ["127.0.0.1:8888"]
use_tls = false  
sni = "admin.example.com"
waf_rules = "admin"

[upstreams.test]
addrs = ["127.0.0.1:8181"]
use_tls = false  
sni = "test.example.com"
waf_rules = "admin"

# Опциональная секция для настройки tracing
[tracing]
level = "info"  # или "trace", "info", "warn", "error", "debug"
output = "file"  # "console", "json", "both"
enable_ansi = true